// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: rpc_error.proto

package rpcerror

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type RPCError struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          int32                  `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Details       string                 `protobuf:"bytes,3,opt,name=details,proto3" json:"details,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RPCError) Reset() {
	*x = RPCError{}
	mi := &file_rpc_error_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RPCError) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RPCError) ProtoMessage() {}

func (x *RPCError) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_error_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RPCError.ProtoReflect.Descriptor instead.
func (*RPCError) Descriptor() ([]byte, []int) {
	return file_rpc_error_proto_rawDescGZIP(), []int{0}
}

func (x *RPCError) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *RPCError) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *RPCError) GetDetails() string {
	if x != nil {
		return x.Details
	}
	return ""
}

var File_rpc_error_proto protoreflect.FileDescriptor

const file_rpc_error_proto_rawDesc = "" +
	"\n" +
	"\x0frpc_error.proto\x12\brpcerror\"R\n" +
	"\bRPCError\x12\x12\n" +
	"\x04code\x18\x01 \x01(\x05R\x04code\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12\x18\n" +
	"\adetails\x18\x03 \x01(\tR\adetailsB\fZ\n" +
	".;rpcerrorb\x06proto3"

var (
	file_rpc_error_proto_rawDescOnce sync.Once
	file_rpc_error_proto_rawDescData []byte
)

func file_rpc_error_proto_rawDescGZIP() []byte {
	file_rpc_error_proto_rawDescOnce.Do(func() {
		file_rpc_error_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_rpc_error_proto_rawDesc), len(file_rpc_error_proto_rawDesc)))
	})
	return file_rpc_error_proto_rawDescData
}

var file_rpc_error_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_rpc_error_proto_goTypes = []any{
	(*RPCError)(nil), // 0: rpcerror.RPCError
}
var file_rpc_error_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_rpc_error_proto_init() }
func file_rpc_error_proto_init() {
	if File_rpc_error_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_rpc_error_proto_rawDesc), len(file_rpc_error_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_rpc_error_proto_goTypes,
		DependencyIndexes: file_rpc_error_proto_depIdxs,
		MessageInfos:      file_rpc_error_proto_msgTypes,
	}.Build()
	File_rpc_error_proto = out.File
	file_rpc_error_proto_goTypes = nil
	file_rpc_error_proto_depIdxs = nil
}
